# Generated by Django 3.1.4 on 2021-01-04 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SOME STRING', max_length=50)),
                ('dob', models.DateField()),
                ('achievements', models.CharField(default='SOME STRING', max_length=50)),
                ('address', models.CharField(default='SOME STRING', max_length=50)),
                ('pno', models.PositiveIntegerField()),
                ('education', models.CharField(default='SOME STRING', max_length=50)),
                ('role', models.CharField(default='SOME STRING', max_length=50)),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.manager')),
            ],
        ),
    ]
