# Generated by Django 3.1.4 on 2021-01-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_auto_20210105_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('APR', 'approved'), ('PND', 'pending'), ('RJT', 'rejected')], default='pending', max_length=10),
        ),
    ]
