# Generated by Django 3.1.4 on 2021-01-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_auto_20210106_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('APR', 'approved'), ('PND', 'pending'), ('RJT', 'rejected')], default='PND', max_length=10),
        ),
    ]
