# Generated by Django 3.1.4 on 2021-01-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_auto_20210106_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='manager_id',
            new_name='m',
        ),
    ]
