# Generated by Django 3.1.4 on 2021-01-04 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=50)),
                ('opposition', models.CharField(max_length=50)),
                ('match_type', models.CharField(choices=[('ODI', 'One Day'), ('T20', 'Twenty'), ('TST', 'Test')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('BAT', 'batsmen'), ('BOWL', 'bowler'), ('ALR', 'all rounder')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Player_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('ODI', 'One Day'), ('T20', 'Twenty'), ('TST', 'Test')], max_length=7)),
                ('strike_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wickets', models.PositiveSmallIntegerField()),
                ('runs', models.PositiveIntegerField()),
                ('is_available', models.BooleanField()),
                ('economy', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
        migrations.CreateModel(
            name='MatchSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='players.fixture')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
    ]
