# Generated by Django 3.1.4 on 2021-01-05 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletePlayer',
            fields=[
                ('player_id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('role', models.CharField(max_length=25)),
                ('match_type', models.CharField(max_length=25)),
                ('strike_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wickets', models.PositiveSmallIntegerField()),
                ('runs', models.PositiveIntegerField()),
                ('is_available', models.BooleanField()),
                ('economy', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='players.player'),
        ),
        migrations.DeleteModel(
            name='MatchSelection',
        ),
    ]
